# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetStackComponentResult',
    'AwaitableGetStackComponentResult',
    'get_stack_component',
    'get_stack_component_output',
]

@pulumi.output_type
class GetStackComponentResult:
    """
    A collection of values returned by getStackComponent.
    """
    def __init__(__self__, configuration=None, connector_resource_id=None, connectors=None, created=None, flavor=None, id=None, labels=None, name=None, type=None, updated=None, workspace=None):
        if configuration and not isinstance(configuration, dict):
            raise TypeError("Expected argument 'configuration' to be a dict")
        pulumi.set(__self__, "configuration", configuration)
        if connector_resource_id and not isinstance(connector_resource_id, str):
            raise TypeError("Expected argument 'connector_resource_id' to be a str")
        pulumi.set(__self__, "connector_resource_id", connector_resource_id)
        if connectors and not isinstance(connectors, list):
            raise TypeError("Expected argument 'connectors' to be a list")
        pulumi.set(__self__, "connectors", connectors)
        if created and not isinstance(created, str):
            raise TypeError("Expected argument 'created' to be a str")
        pulumi.set(__self__, "created", created)
        if flavor and not isinstance(flavor, str):
            raise TypeError("Expected argument 'flavor' to be a str")
        pulumi.set(__self__, "flavor", flavor)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if labels and not isinstance(labels, dict):
            raise TypeError("Expected argument 'labels' to be a dict")
        pulumi.set(__self__, "labels", labels)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if type and not isinstance(type, str):
            raise TypeError("Expected argument 'type' to be a str")
        pulumi.set(__self__, "type", type)
        if updated and not isinstance(updated, str):
            raise TypeError("Expected argument 'updated' to be a str")
        pulumi.set(__self__, "updated", updated)
        if workspace and not isinstance(workspace, str):
            raise TypeError("Expected argument 'workspace' to be a str")
        pulumi.set(__self__, "workspace", workspace)

    @property
    @pulumi.getter
    def configuration(self) -> Mapping[str, str]:
        return pulumi.get(self, "configuration")

    @property
    @pulumi.getter(name="connectorResourceId")
    def connector_resource_id(self) -> str:
        return pulumi.get(self, "connector_resource_id")

    @property
    @pulumi.getter
    def connectors(self) -> Sequence['outputs.GetStackComponentConnectorResult']:
        return pulumi.get(self, "connectors")

    @property
    @pulumi.getter
    def created(self) -> str:
        return pulumi.get(self, "created")

    @property
    @pulumi.getter
    def flavor(self) -> str:
        return pulumi.get(self, "flavor")

    @property
    @pulumi.getter
    def id(self) -> Optional[str]:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def labels(self) -> Mapping[str, str]:
        return pulumi.get(self, "labels")

    @property
    @pulumi.getter
    def name(self) -> Optional[str]:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def type(self) -> Optional[str]:
        return pulumi.get(self, "type")

    @property
    @pulumi.getter
    def updated(self) -> str:
        return pulumi.get(self, "updated")

    @property
    @pulumi.getter
    def workspace(self) -> Optional[str]:
        return pulumi.get(self, "workspace")


class AwaitableGetStackComponentResult(GetStackComponentResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetStackComponentResult(
            configuration=self.configuration,
            connector_resource_id=self.connector_resource_id,
            connectors=self.connectors,
            created=self.created,
            flavor=self.flavor,
            id=self.id,
            labels=self.labels,
            name=self.name,
            type=self.type,
            updated=self.updated,
            workspace=self.workspace)


def get_stack_component(id: Optional[str] = None,
                        name: Optional[str] = None,
                        type: Optional[str] = None,
                        workspace: Optional[str] = None,
                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetStackComponentResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    __args__['type'] = type
    __args__['workspace'] = workspace
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('zenml:index/getStackComponent:getStackComponent', __args__, opts=opts, typ=GetStackComponentResult, package_ref=_utilities.get_package()).value

    return AwaitableGetStackComponentResult(
        configuration=pulumi.get(__ret__, 'configuration'),
        connector_resource_id=pulumi.get(__ret__, 'connector_resource_id'),
        connectors=pulumi.get(__ret__, 'connectors'),
        created=pulumi.get(__ret__, 'created'),
        flavor=pulumi.get(__ret__, 'flavor'),
        id=pulumi.get(__ret__, 'id'),
        labels=pulumi.get(__ret__, 'labels'),
        name=pulumi.get(__ret__, 'name'),
        type=pulumi.get(__ret__, 'type'),
        updated=pulumi.get(__ret__, 'updated'),
        workspace=pulumi.get(__ret__, 'workspace'))
def get_stack_component_output(id: Optional[pulumi.Input[Optional[str]]] = None,
                               name: Optional[pulumi.Input[Optional[str]]] = None,
                               type: Optional[pulumi.Input[Optional[str]]] = None,
                               workspace: Optional[pulumi.Input[Optional[str]]] = None,
                               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetStackComponentResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    __args__['type'] = type
    __args__['workspace'] = workspace
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('zenml:index/getStackComponent:getStackComponent', __args__, opts=opts, typ=GetStackComponentResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetStackComponentResult(
        configuration=pulumi.get(__response__, 'configuration'),
        connector_resource_id=pulumi.get(__response__, 'connector_resource_id'),
        connectors=pulumi.get(__response__, 'connectors'),
        created=pulumi.get(__response__, 'created'),
        flavor=pulumi.get(__response__, 'flavor'),
        id=pulumi.get(__response__, 'id'),
        labels=pulumi.get(__response__, 'labels'),
        name=pulumi.get(__response__, 'name'),
        type=pulumi.get(__response__, 'type'),
        updated=pulumi.get(__response__, 'updated'),
        workspace=pulumi.get(__response__, 'workspace')))
