[project]
name = "sfn-orchestrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["boto3", "zenml>=0.73.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
